import com.drools.DroolsDemo.models.Order;
import com.drools.DroolsDemo.utils.LoggerUtil;
import com.drools.DroolsDemo.models.Status;

global java.lang.Integer minimumOrderPurchaseValue;

rule "MiniOrder"
    when
        $order: Order(amount < 5);
    then
        $order.setTax(10.2);
        $order.calculateTotalAmount();
        $order.modifyOrderStatus(minimumOrderPurchaseValue, $order.getTotalAmount());
        LoggerUtil.logValue($order);
end

rule "MediumOrder"
    when
        order: Order(amount >= 5 && amount <= 10);
    then
        order.setTax(15.1);
        order.calculateTotalAmount();
        order.modifyOrderStatus(minimumOrderPurchaseValue, order.getTotalAmount());
        LoggerUtil.logValue(order);
end

rule "MaxOrder"
    when
        order: Order(amount > 10);
    then
        order.setTax(20.3);
        order.calculateTotalAmount();
        order.modifyOrderStatus(minimumOrderPurchaseValue, order.getTotalAmount());
        LoggerUtil.logValue("Updated order value is, " + order.toString());
end

rule "SuperOrder" salience -20
    when
        /*This is an and condition*/
        order: Order(amount > 100);
        Order(id%2 == 0);
    then
        order.setTax(28.3);
        order.calculateTotalAmount();
        order.modifyOrderStatus(minimumOrderPurchaseValue, order.getTotalAmount());
        LoggerUtil.logValue("Updated order value is, " + order.toString());
end